name: matterhorn
base: core18
adopt-info: matterhorn
summary: Matterhorn
description: |
  A feature-rich Unix terminal client for the Mattermost chat system
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  matterhorn:
    command: matterhorn
    plugs:
      - home
      - desktop
      - network
      - password-manager-service

parts:
  matterhorn:
    plugin: nil
    override-build: |
      set -eu
      ARCHITECTURE=$(dpkg --print-architecture)
      echo "Get GitHub releases..."
      wget --quiet https://api.github.com/repos/matterhorn-chat/matterhorn/releases -O releases.json
      VERSION=$(jq . releases.json | grep tag_name | cut -d'"' -f4 | sed s'/v//' | head -n 1)
      TAR_URL=$(grep browser_download releases.json | grep "download/${VERSION}/" | grep ubuntu | cut -d'"' -f4)
      TAR=$(basename "${TAR_URL}")
      echo "Downloading ${TAR_URL}..."
      wget "${TAR_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${TAR}"
      echo "Unpacking ${TAR}..."
      tar jxvf "${SNAPCRAFT_PART_INSTALL}/${TAR}" -C ${SNAPCRAFT_PART_INSTALL}
      rm -f releases.json
      rm -f "${SNAPCRAFT_PART_INSTALL}/${TAR}"
      snapcraftctl set-version "$VERSION"
    build-packages:
      - wget
      - jq
    stage-packages:
      - libsecret-tools
      - libnotify-bin
      - xclip

